### ISSUE TITLE
iOS Notifications

### ISSUE THREAD

**Issue by aerosol** [tooot-app/app#176]
Hello, thank you for this app, I'm really enjoying it. Are iOS notifications on the roadmap by any chance?

**Comment by xmflsct** [comment]
Hi, thanks for your support. tooot has notification support already. Maybe it is not so obvious in the interface - something I need to change. It is the bell icon next to the edit profile button. In there you can enable notification. Let me know if it works.

**Comment by aerosol** [comment]
Amazing, completely missed that! ♥️🙌 thanks again
