### ISSUE TITLE
Android cannot login

### ISSUE THREAD

**Issue by Y32Gcnte8z** [tooot-app/app#187]
After I input the domain of instance and then click the button Login, the app is not responding.

**Comment by buzhangjiuzhou** [comment]
> After I input the domain of instance and then click the button Login, the app is not responding.

This problem happened to me and another person, I found out that it happens when the default browser is changed, you can change it back to default.

However, this is a BUG, wish to be fixed by author!

**Comment by xmflsct** [comment]
@buzhangjiuzhou thanks for the feedback! I will take a look.

**Comment by xmflsct** [comment]
@Y32Gcnte8z @buzhangjiuzhou can you have a try with the latest version v3.2? Thanks!

**Comment by Y32Gcnte8z** [comment]
> @Y32Gcnte8z @buzhangjiuzhou can you have a try with the latest version v3.2? Thanks!

the problem still exists

**Comment by buzhangjiuzhou** [comment]
> > @Y32Gcnte8z @buzhangjiuzhou can you have a try with the latest version v3.2? Thanks!
> 
> the problem still exists

Have logged in, the change of default browser didn't affect the use of tooot.

But when I logged out and trying to log in again, the problem still exists.

**Comment by Y32Gcnte8z** [comment]
> @Y32Gcnte8z @buzhangjiuzhou can you have a try with the latest version v3.2? Thanks!

再补充一点信息：默认浏览器为Chrome的时候，可以正常打开登陆页面，但是默认浏览器换成Firefox就不行了。

**Comment by th0mcat** [comment]
Can confirm problem still exists on v3.5, tried defaulting my browser back to chrome, cleared Tooot's cache and storage, and tried to login again, still unable to login.

**Comment by kytrun** [comment]
A similar error occurred in other React Native applications due to the `target` attribute of the URL tag.

**Comment by xmflsct** [comment]
Close due to outdated
