### ISSUE TITLE
[Enhancement] Hide posts with content warnings

### ISSUE THREAD

**Issue by ThatOneCalculator** [tooot-app/app#199]
Like Tusky, posts with CWs should be hidden by default with an expand button

**Comment by xmflsct** [comment]
Thanks for the report! I just tried CW and it is working as expected.

Maybe you have turned on always expanding CW on the instance? The app reads this setting and applies it.

Let me know if this is the case. Thanks.

**Comment by ThatOneCalculator** [comment]
Ah yea, that fixes it. Ty!

**Comment by xmflsct** [comment]
No problem!
