### ISSUE TITLE
Translation doesn't work

### ISSUE THREAD

**Issue by hellojaccc** [tooot-app/app#203]
iOS 15, South Korea

https://user-images.githubusercontent.com/71537512/151970542-c7948a86-32d1-4d4e-a01f-a2f43d8b5ef8.MOV

Tried another languages, it didn't work.

**Comment by xmflsct** [comment]
Thanks for the report! I have seen some error reports and it is known.

Though I am curious about your use case here. From the video I can see that your OS's language is in Korean, and tooot would default to use English as app's language. Are you expecting to be able to translate toots into English or Korean? The current functionality would default to translate to English (or the same as app's language setting).

**Comment by hellojaccc** [comment]
Thanks for checking out :) It's a great app.
I only understand english & korean so i wanted to translate that chinese(?or japanese) toot to english. 

By the way, can i translate the app to korean?

**Comment by xmflsct** [comment]
Thank you! I will fix this soon.

If you would like to contribute to translating the app, you can do it here https://crowdin.tooot.app/. After the app has been translated to at least say 90%, I can release this new language.

**Comment by xmflsct** [comment]
The app has been updated to v3.2.1. It will auto update the next time you open the app. So the second time you open the app, you should be able to see the version number in the settings. The translation should be working now. Let me know if it still doesn't work!
