### ISSUE TITLE
Make the account switcher one-handed friendly

### ISSUE THREAD

**Issue by MaybeThisIsRu** [tooot-app/app#239]
Currently, the account switcher that is toggled by holding a tap on the profile icon in the bottom right - it shows all the accounts at the top of the bar that comes up. Instead, if they were shown close to the bottom where the profile icon is, it would help ease navigation burden on the fingers. Especially given how large phones tend to be these days.

**Comment by xmflsct** [comment]
Haha thanks for the report! I myself intentionally bought a smaller phone therefore I am used to comfortably operating apps with one hand.

**Comment by xmflsct** [comment]
Fixed in v3.5.4

**Comment by MaybeThisIsRu** [comment]
Received this update. Fantastic work, thank you!
