### ISSUE TITLE
Logging out of one account doesn't update profile page to the other

### ISSUE THREAD

**Issue by MaybeThisIsRu** [tooot-app/app#245]
How to reproduce:

1. Add two accounts.
2. Switch to the one that you want to log out from.
3. Log out.
4. Profile page switches to the other account, but toots count, following count, followers count all are from the account you just logged out from.

**Comment by xmflsct** [comment]
Fixed by https://github.com/tooot-app/app/commit/7f8a8de898ea1be3b1fa3c4692ef1808a1ce2f1e
