### ISSUE TITLE
remember read post and stick to that position in timeline

### ISSUE THREAD

**Issue by foss-** [tooot-app/app#246]
**Currently**
When refreshing timeline, view jumps to latest post.

**Expected**
Stay on last read post to allow users to read through their timeline old to new. Not sure if this should be default or optional, but it is how some users read their timeline. Losing your place in the timeline on every refresh is rather inconvenient. Refresh 2-3 times and you are lost.

EDT: to get an idea how this can be implemented, iirc Mastodon for iOS does this quite nicely.

**Comment by xmflsct** [comment]
Hey, it is a known limitation of React Native. I tried to work around this limitation but may be broken again. Let me look into it.

**Comment by chrisonline** [comment]
Any news about this?

**Comment by foss-** [comment]
If functionality has been removed, why not keep this issue open as feature request?
