### ISSUE TITLE
Friendica shows that Toot has been authorized but Toot acts like it isnt

### ISSUE THREAD

**Issue by DetroitLibertyPenguin** [tooot-app/app#247]
Enter instances name as libranet.de takes to website, log in, select YES to authorize, never returns to app automatically, when manually returning it is same as first time with no data shown webpage shows I authorized toot 3 times
![2DE64B54-01F7-4BD8-9692-9BF96FA930A4](https://user-images.githubusercontent.com/65328167/159583432-c283003a-b3c1-4ec3-8168-3ed95268786d.png)

**Comment by xmflsct** [comment]
Hi, unfortunately I am not able to check all none Mastodon instances.
