### ISSUE TITLE
Open profile with another account

### ISSUE THREAD

**Issue by MaybeThisIsRu** [tooot-app/app#271]
It would be great to have an option where you can re-open the profile you are viewing but with another one of your accounts that are you logged in with.

**Comment by xmflsct** [comment]
hmmm, interesting use case. I guess the goal is to follow an account with another account?

**Comment by xmflsct** [comment]
It is actually not that straightforward. Currently with an active account, when you visit a profit the app can tell you if you have followed that account or not. If yes, that button becomes "unfollow". In this case, it would be unintuitive to long tap this "unfollow" button to open up a dialog box for following. It is the same situation for like and boost as there is a state involved.

Another difficulty is that, a target account will have different user IDs on different instances. This means that, to call a target account on a different instance, a search action needs to take place first to get the user ID. This step could easily go wrong as many instances are running under limited resources.

The last tricky bit I can think of right now is around error scenarios. Currently the app "assumes" most API calls would succeed, therefore only warn users in few known scenarios, of course to reduce the complexity of development. As described above, many steps are needed to manage cross instance action, and if any of the step failed, it would be great to provide a meaningful error message and that is not an easy task - not to mention tooot relies on volunteers for translations.

So unfortuantely probably in the short term, I will leave this issue open until there is enough motivation to tackle this complexity.
