### ISSUE TITLE
One should be able to boost their own followers-only toots

### ISSUE THREAD

**Issue by MaybeThisIsRu** [tooot-app/app#274]
The web UI allows you to boost your own toots, even if they are followers only.

However, tooot doesn't let you do this. This is a bug and should be fixed.

**Comment by MaybeThisIsRu** [comment]
Sorry, just clarifying, does https://github.com/tooot-app/app/commit/ee2f23c9721c4a40cee5c7010768199c6f18d55d only apply to your own toots?

**Comment by xmflsct** [comment]
Sorry totally missed that part, it should be only to my own toots. Will patch it soon.

**Comment by MaybeThisIsRu** [comment]
No worries! Thanks for your work. :)
