### ISSUE TITLE
Timeline does not start at the top

### ISSUE THREAD

**Issue by junochat** [tooot-app/app#326]
Current version: 4.0.4, iOS

Opening up the app, the timelines position starts about 1/3 from the top of the viewport.

Switching to other timelines like home, federated, notifications, or even profile pages is also the same: about a third from the top of the viewport, as indicated by the scrollbar.

When focussed on a specified toot, it’s also much of the same: if there are comments, the page opens about 1/3 down -- but if there are no comments (nothing to scroll) then it’s just a wide gap above the toot.

![1DF3B7BE-953C-43CF-8E6C-BFB1BF4BF6F7](https://user-images.githubusercontent.com/22552372/172852972-02f881ee-32bd-4423-bcc3-f3da5f8d509f.jpeg)
![37F7F6F6-8855-4C43-9ACC-E34F29932C66](https://user-images.githubusercontent.com/22552372/172852978-3c3f56ac-aefd-4b6d-a9dc-d077dbb39f11.jpeg)

**Comment by xmflsct** [comment]
Thanks for reporting! A fix is on the way, https://github.com/tooot-app/app/commit/6f414d38be713d28d9b0995f321d6c61bd583316
