### ISSUE TITLE
When uploading media, make it clear if all metadata is removed (or if it isn't).

### ISSUE THREAD

**Issue by MaybeThisIsRu** [tooot-app/app#385]
I have lately gotten in the habit of sharing the source image directly, and none of the apps I use ever tell me if metadata is removed by them or left in. This causes me a lot of worry about any GPS data on my images/videos.

I'd love it if tooot made it clear before I uploaded an image/video how it treats metadata. This can be some sort of help text in a dialog box before the upload is started.

**Comment by xmflsct** [comment]
Good point. The latest version has been using this library https://github.com/react-native-image-picker/react-native-image-picker. And I have instructed this library to exclude any metadata, see this line https://github.com/tooot-app/app/blob/main/src/components/mediaSelector.ts#L69.

Let me think of a way to not inform this detail to the users in a none intrusive way. Do not want yet another dialog box in the process. :)

**Comment by consoleaf** [comment]
Could have a checkbox set to remove the metadata by default

Either:
- [x] Remove metadata
- [ ] Keep metadata

Alternatively, you could make a button to show a list of metadata fields that will be uploaded

**Comment by consoleaf** [comment]
> you need to remember which apps strip metadata and which ones don't

Not if the checkbox is shown when uploading or when posting
