### ISSUE TITLE
Attaching Media 

### ISSUE THREAD

**Issue by scottiefalkon** [tooot-app/app#407]
When tapping the icon to attach media, the dialog reappears after choosing media type, making user select type again before media picker will open.

**Comment by xmflsct** [comment]
@scottiefalkon Which OS are you using? And which version of the app do you have? If you haven't updated to the latest version (v.4.3.4), can you have a try to see if the issue persists. Thanks!

**Comment by scottiefalkon** [comment]
Android 13, Tooot 4.3.4

**Comment by xmflsct** [comment]
Cannot reproduce in the emulator. Soon will publish an updated version and maybe you can try again in there?

**Comment by xmflsct** [comment]
Will close the issue for now
