### ISSUE TITLE
Quote-boost support

### ISSUE THREAD

**Issue by limdingwen** [tooot-app/app#410]
Hi! Second request.

https://mastodon.social/@IgnisIncendio/109215236990098670

The app is able to show a preview of the toot linked, which is great! However, it attempts to open the link in an external browser. I think it might be better if it is able to detect that it is an ActivityPub post (how?) and open the toot within the app instead.

**Comment by xmflsct** [comment]
I thought I had developed this feature, and yes I did, https://github.com/tooot-app/app/blob/main/src/components/openLink.ts#L42L71.

This might not always work though. If your instance has not retrived this content, then the search would fail and therefore opening in a browser.
