### ISSUE TITLE
上傳圖片延遲&表情邊界問題

### ISSUE THREAD

**Issue by jimmyorz** [tooot-app/app#436]
兩個問題一起回報

1. 圖片上傳有延遲
發嘟時若有夾帶圖片或影片，雖然進度顯示上傳完成，但實際上要試圖片張數等約10秒以上才能成功發出去，不少第三方App都有問題，但官方App沒有，不確定是不是第三方API的問題，這一點有非常多嘟友反應。
https://user-images.githubusercontent.com/66128107/200115878-37a6bda4-f500-4bbf-9237-262224c8c485.MOV

2. 表情邊界問題
詳細見本串討論：https://g0v.social/@hjhmi89/109289649820405272
我自己是碰到拉到右側底部的時候，會偶發邊界錯亂的問題，然後往左拉回去也會跟著出問題。
https://user-images.githubusercontent.com/66128107/200116067-a0516f8d-adbc-453c-ab74-1b8a2347114c.MOV
但有其它嘟友比較嚴重，整個白的蓋板只能重開
![image](https://user-images.githubusercontent.com/66128107/200116141-25909719-e422-4fc9-a4e1-9ea45c8974f8.png)
影片：https://g0v.social/@hjhmi89/109290651874446234

再次謝謝作者🙏

**Comment by xmflsct** [comment]
--- 1 ---
非常有意思的发现！估计第三方app都默认，当附件上传成功之后即可使用，但其实API会返回“不能附加还在处理中的文件。请稍后再试！”。很可惜Mastodon的API文档质量不高，特别是当他们发布官方app之后就几乎不更新API文档了，第三方app开发者要花很多时间去理解Mastodon是怎么运作的。

我看了一下文档（https://docs.joinmastodon.org/methods/statuses/media/#:~:text=GET-,Update%20attachment,-https%3A//mastodon.example），觉得有可能是官方app知道这个细节，所以会查询图片是否已经处理成功，才允许发嘟。我试了一下官方的app，在图片上传成功之后还不能立即发嘟，还需要等个几秒钟，应该就是这个逻辑。之后我可以添加这个功能。

--- 2 ---
这个我复现不了哎。我多观察看看再来反馈。

**Comment by jimmyorz** [comment]
> --- 1 --- 非常有意思的发现！估计第三方app都默认，当附件上传成功之后即可使用，但其实API会返回“不能附加还在处理中的文件。请稍后再试！”。很可惜Mastodon的API文档质量不高，特别是当他们发布官方app之后就几乎不更新API文档了，第三方app开发者要花很多时间去理解Mastodon是怎么运作的。
> 
> 我看了一下文档（ https://docs.joinmastodon.org/methods/statuses/media/#:~:text=GET-,Update%20attachment,-https%3A//mastodon.example ），觉得有可能是官方app知道这个细节，所以会查询图片是否已经处理成功，才允许发嘟。我试了一下官方的app，在图片上传成功之后还不能立即发嘟，还需要等个几秒钟，应该就是这个逻辑。之后我可以添加这个功能。
> 
> --- 2 --- 这个我复现不了哎。我多观察看看再来反馈。

2的部份我昨天後來又試了一下
發現可能是兩種問題其中一個
(1) 不同機型配置
iPad Air 5無此問題，但iPhone 11有
但嘟友整個白掉的部份我也無法重現，我再請他移除重裝看看
順便也問問機型

(2) 常用計數0跟20（iPad無此問題）
在重新安裝還沒有使用任何貼圖，也沒有「常用」欄位的情況下很容易重現邊界溢出的情況
但隨便點一個讓常用欄位出現後，會發現很難重現了
不過當常用的數量超過20滿了之後又可以很容易重現了

順帶一提，這邊也發現常用的順序似乎反了？
App目前的邏輯是把新用的貼圖放到常用的最後面
但一般類似的App會放在最前面
放在最後面也會造成一個問題
當20滿了之後後面就不會再更新了，只會顯示最早使用的20個貼圖

謝謝🙏

**Comment by jimmyorz** [comment]
今早詢問有類似該情況的嘟友
很巧合的是，出問題的機型和我一樣都是iPhone 11
但他目前重新安裝和重開機都無法排除
可能真的是特定機型的問題了lol

**Comment by xmflsct** [comment]
@jimmyorz 看截图系统是iOS 16？

**Comment by jimmyorz** [comment]
> @jimmyorz 看截图系统是iOS 16？
是的，都是iOS 16

但iPad Air 5同樣是iOS 16卻沒有此問題

**Comment by xmflsct** [comment]
@jimmyorz 我试了iOS 16和16.1的iPhone 11模拟器，暂时没办法复现哎。你们有没有用非官方第三方键盘？

**Comment by xmflsct** [comment]
我这里试了一个第三方键盘没有办法复现。看到另一位嘟友使用了Assistive Touch并且在底部，试了一下也没有发现问题。

**Comment by jimmyorz** [comment]
> 我这里试了一个第三方键盘没有办法复现。看到另一位嘟友使用了Assistive Touch并且在底部，试了一下也没有发现问题。

均是使用系統內建輸入法，沒有使用第三方
剛剛稍微滑一下偶爾還是會邊界溢出
https://user-images.githubusercontent.com/66128107/200198616-9d4125c8-4245-459a-9e58-e8eb517a8f23.MOV

如果真的沒辦法重現的話，就暫時先擱置吧
謝謝你花了兩天時間一直幫忙檢查這個🙏

**Comment by xmflsct** [comment]
@jimmyorz 不谢不谢！我现在明白了你的意思了。我之前一直想重现另外一位嘟友那种整页都被占满的状况，因为那种情况有可能是因为计算屏幕尺寸错误，所以问你们有没有用第三方键盘。

如果是向右侧滑出边界的问题的话，我自己也有碰到过，让我看看是因为什么问题：）

**Comment by jimmyorz** [comment]
回報一下。
嘟友今天開App的時候發現表情整個白掉的問題解決了
暫時不知道是因為您更新新版，還是因為站點更新了3.5.5

**Comment by xmflsct** [comment]
那我先关闭这个issue啦，如果以后还有碰到类似情况的话再开～
