### ISSUE TITLE
Error when favorite toot on Android

### ISSUE THREAD

**Issue by X-static** [tooot-app/app#437]
App version: 4.5.0
Android 12, Poco F3

I have this error everytime I try to favorite a toot.
This doesn't happen on the version 3.4.3 (the one on play store).

![Screenshot_2022-11-05-09-47-22-777_com xmflsct app tooot](https://user-images.githubusercontent.com/3238301/200127626-698a07e5-7e0c-4e46-b5e9-b3e3d8d8e8b2.png)

**Comment by xmflsct** [comment]
Fixed in https://github.com/tooot-app/app/issues/433
Release coming soon
