### ISSUE TITLE
Three Dot Menu in Posts still not working

### ISSUE THREAD

**Issue by scottiefalkon** [tooot-app/app#451]
I know we discussed this before. You said you can't reproduce it in the emulator. On the newest version of tooot and the latest version of Android 13 on Pixel 6 Pro, tapping the "..."  in a post does nothing. Neither in timeline view or in a post itself. I even did a clean install the other night of the entire OS. It's not any setting on my end. I'd like to help resolve. What can I do to help?

**Comment by thigger** [comment]
Reproducible here (Galaxy S21, Android 12) - though if I keep tapping I can sometimes get it to work. I have my font size set to the smallest in Android and screen zoom also at the smallest if that's relevant. Font size in the app is set to "M - default"

**Comment by xmflsct** [comment]
@scottiefalkon I am hoping to push a test version in few days. By then there will be an apk available on GitHub that you can try it out and let me know if it works!

**Comment by scottiefalkon** [comment]
Thank you. Will do.

**Comment by xmflsct** [comment]
@scottiefalkon forgot that I have removed the testing APK builds a while back. Just released 4.6.0. You can find the apk in the release. Let me know if it has been fixed!

**Comment by scottiefalkon** [comment]
> @scottiefalkon forgot that I have removed the testing APK builds a while back. Just released 4.6.0. You can find the apk in the release. Let me know if it has been fixed!

The issue remains. I noticed someone posted a recent review that is experiencing the issue as well. Wish I knew the answer.

**Comment by scottiefalkon** [comment]
> @scottiefalkon with 4.6.0, are you able to trigger the three dot menu every now and then, or it is not possible to trigger it at all?

It won't trigger at all. Same as before.

**Comment by xmflsct** [comment]
Okay so it is not a touch target issue in this case.

**Comment by scottiefalkon** [comment]
I would say not.

**Comment by leohearts** [comment]
Maybe the reason is `onLongPress={() => null}`  in `<Pressable>` above `<ContextMenu>` ?
This makes the three dot menu not triggering even if user move 1px on their finger when touching.
I can only trigger the context menu only when using a mouse  or pressing it very carefully.

**Comment by xmflsct** [comment]
@leohearts I don't think so, that line was added in the latest release v4.6.1 to see if that may solve the problem https://github.com/tooot-app/app/commit/ce0adeeb666b5c906a0b055f9f98609bd17d674e.

I believe it is due to how the layout API has been implemented differently on different Android systems. In the emulator which is based on Google's official interpretation of Android, the current touch target is huge, the same as on iOS. But it may be somehow not rendered in the way it is intended.

If v4.6.1 is still not working for you and others, I have to change the Android specific code to use another approach, which is fine, just a bit annoying to maintain different codes for different systems, which is not the intention of React Native.

**Comment by scottiefalkon** [comment]
It's still not working at all for me on the Pixel 6 Pro. I haven't tried
with a mouse. But, I wouldn't be using one anyway. I have tried to very
carefully tap the area many times. It just won't trigger for me.

**Comment by unixninja92** [comment]
I'm on a pixel 5a. The button worked the first two times I hit it right after opening the app for the first time in a while but hasn't worked since. I'm on 4.6.1.

**Comment by xmflsct** [comment]
Forgot to ask, does the three dot work in the User/Account page?

<img width="369" alt="image" src="https://user-images.githubusercontent.com/292204/202862627-d65fed4f-bc84-4bac-b58f-1170f3dfbc4f.png">

**Comment by unixninja92** [comment]
The three dots on account pages work just fine.

**Comment by xmflsct** [comment]
@unixninja92 Thank you, this is helpful!

**Comment by scottiefalkon** [comment]
This is great to see. Fingers crossed.

**Comment by xmflsct** [comment]
v4.6.2 released hoping it would be possible to address this issue. Would any of you like to try it out and let me know? Thanks!

**Comment by scottiefalkon** [comment]
Unfortunately, still doesn't work at all for me. Pixel 6 Pro, Android 13,
tooot 4.6.2

**Comment by thigger** [comment]
Sorry, similar here. I can trigger it but only on about 1 in 10 presses (if anything it seems to be triggering less frequently than before). Galaxy S21, Android 12, tooot 4.6.2 (Play Store)

**Comment by ottomano** [comment]
Same problem here on 4.6.2 (Xiaomi Mi A2 Lite, Android 10).

Please notice that **Tooot app has disappeared from google play**.

**Comment by scottiefalkon** [comment]
It is gone again. It was there 3-4 hours ago.

**Comment by xmflsct** [comment]
Because Play Store's staff also could not click the menu in order to test blocking accounts..

**Comment by scottiefalkon** [comment]
Makes sense. I hate that this is being such an aggravating issue. Hopefully
you'll have it solved soon. The app is by far the best looking and
performing one available for Android. We do need that menu though.

Appreciate all your work.

**Comment by ottomano** [comment]
> v4.6.2 released hoping it would be possible to address this issue. Would any of you like to try it out and let me know? Thanks!

Since the issue is still present on 4.6.2, i you would like to test a 4.6.3 beta version of the APK, I'm available to try it in order to see if the fix is properly working.

**Comment by scottiefalkon** [comment]
I'm definitely willing to try out a beta as well if that will help.

**Comment by scottiefalkon** [comment]
Fixed! Fantastic. Thanks a bunch!
