### ISSUE TITLE
Add support for RTL languages

### ISSUE THREAD

**Issue by do87** [tooot-app/app#452]
At the moment toots are displayed LTR by default

**Comment by xmflsct** [comment]
Are you asking about the entire interface supporting a language that is RTL? Or is it about showing RTL when a toot is in a language that is RTL?

Besides, are you using iOS or Android? They seem to provide different type of writing direction support, therefore asking.

**Comment by do87** [comment]
I'm using iOS
and you're correct, when a toot is written in RTL language it should be displayed RTL
