### ISSUE TITLE
Closing app stops system music from playing

### ISSUE THREAD

**Issue by recombinatrix** [tooot-app/app#470]
Every time I close Tooot,  background audio that was playing in another app stops.

iPhone 13 Pro Max
iOS 16.6.1
Toot version 4.6.1

Steps to replicate:  

Play some audio in some other app.
Switch to tooot.
Go back to the home screen by swiping up.
Other app's audio stops playing by fading out.

I have replicated this with audio playing from Apple Music, Pocketcasts, and Tidal.

No idea what kind of log files or other data I could provide to help with debugging, but if there is something please let me know and I'll provide it.

**Comment by xmflsct** [comment]
Thanks for the report. It is a known issue and I am looking into it. Closing due to duplicate at https://github.com/tooot-app/app/issues/441.
