### ISSUE TITLE
Follow tags

### ISSUE THREAD

**Issue by xmflsct** [tooot-app/app#471]
Introduced in v4.0

**Comment by xmflsct** [comment]
Did not implement listing all followed tags as pagination is not yet available, will be introduced in v4.0.3.

**Comment by scottiefalkon** [comment]
So following tags from the app will be available after that Mastodon update?

**Comment by xmflsct** [comment]
@scottiefalkon Yes!

**Comment by scottiefalkon** [comment]
Cool deal. Thanks for all the hard work.
