### ISSUE TITLE
Content warnings in toot composer prevent text after first line from appearing

### ISSUE THREAD

**Issue by alexreid** [tooot-app/app#472]
On iOS 16.1 and Tooot 4.6.1, when composing a toot with a content warning, the text disappears after the first line, where it would usually wrap. Adding a new line character can cause it to reappear for a brief moment. See the attached video to see this bug in action!

<video src="https://user-images.githubusercontent.com/2099579/202910190-e7911e03-7ba4-46e1-a6f2-ffd9abe23f29.MOV">video link: https://user-images.githubusercontent.com/2099579/202910190-e7911e03-7ba4-46e1-a6f2-ffd9abe23f29.MOV</video>

**Comment by xmflsct** [comment]
I have received one other report about this, but unfortunately I cannot reproduce it.

Are there special font settings you have applied in the system settings?

**Comment by alexreid** [comment]
Yes, I have my system font size set to one notch lower than the default. However, I tried setting a 100% font size for Tooot only using the font size widget in Control Center and it didn't fix the problem, and neither did setting Tooot to use the system font size (I also restarted my phone after setting the font size to default, which did not fix it either).

If I set the font size in Tooot's settings to 'L' or 'S' instead of 'M' it does seem to fix the problem, regardless of my system font size.

I'm using an iPhone 14 Pro with the default 'display zoom' setting, if that helps narrow it down! I'm happy to help debug this any way I can.

**Comment by alexreid** [comment]
One more thing I've noticed while testing this issue again: it only repros if there's one line of text in the content warning text box. Once the content warning spans multiple lines (either by adding a new line to it manually or by it being long enough to wrap) the missing text comes back

**Comment by xmflsct** [comment]
Thanks for all the context. I am using the same phone however I still cannot reproduce the issue..

**Comment by xmflsct** [comment]
^ it was a wrong commit tag

**Comment by xmflsct** [comment]
Hi all, can you update to v4.6.6 and see if the issue goes away? If not, does it happen each every time you use CW?

**Comment by alexreid** [comment]
I can verify that it still happens with 4.6.6. It happens any time the composer has a a content warning, including composing a new toot and replying to one with a content warning. The moment the content warning is removed, the missing text in the toot body reappears.

**Comment by de1acr0ix** [comment]
@xmflsct I can see this is still happening in latest 4.7.0 as well. I played with the styles a bit and it seems that if `borderBottomWidth` is set everything is going to be right. But it will make the bottom border appear so we also need to set the its color to `backgroundDefaultTransparent`. However I still don't understand why it matters. From inspector I can see the layout is set properly even without that trick (a bug of React Native?). I'll create a PR for Tooot.
