### ISSUE TITLE
The possibility of copying the text

### ISSUE THREAD

**Issue by TheAwiteb** [tooot-app/app#473]
Copy part and copy the entire toot

**Comment by wlonkly** [comment]
I too would love to be able to select part of a toot for copying. (I think that's what @TheAwiteb is asking for, because you can copy entire toots by long-pressing and choosing "Copy Toot".)

**Comment by TheAwiteb** [comment]
> because you can copy entire toots by long-pressing and choosing "Copy Toot".

I can't copy entire toot, i'am using Android version

**Comment by xmflsct** [comment]
@TheAwiteb Android's toot menu is currently broken, on the way to fix it #451.

@wlonkly It is a known React Native limitation very unfortunate. I would love to enable such but it is still not possible. https://github.com/facebook/react-native/issues/33494#issuecomment-1141741386
