### ISSUE TITLE
Not There in Google Play!

### ISSUE THREAD

**Issue by sallyahaj** [tooot-app/app#483]
When I click on the Google Play, I get an error message:
_We're sorry, the requested URL was not found on this server._

I am not sure if this issue all over the world or not.
![Screenshot from 2022-11-22 18-08-21](https://user-images.githubusercontent.com/109706/203316067-84bc685d-f901-4120-8f50-a014533c92b9.png)

**Comment by ottomano** [comment]
Hi, as far as I know, the devs are aware of this problem.

**Comment by xmflsct** [comment]
Indeed it is known, related to https://github.com/tooot-app/app/issues/451.
