### ISSUE TITLE
Can't log in on Android if default browser isn't chrome

### ISSUE THREAD

**Issue by eamodio** [tooot-app/app#489]
I have my default browser set to duckduckgo and pressing the login button in tooot has no effect. But if I set Chrome as my default browser again the login button will work.

**Comment by ottomano** [comment]
I don't know with Duckduckgo, but with Firefox it is working on my phone.

**Comment by eamodio** [comment]
FWIW, both Tusky and the official Mastodon client work fine with DuckDuckGo as the default

**Comment by xmflsct** [comment]
Seems like the same issue here https://github.com/expo/expo/issues/12045
