### ISSUE TITLE
Remember timeline position when opening

### ISSUE THREAD

**Issue by eamodio** [tooot-app/app#490]
Currently when opening Tooot it scrolls me to the top of the timeline and I would love it if it left me in the position I was at last. I believe there is a marker API that can be used to track the read position.

Thanks!

**Comment by xmflsct** [comment]
Yes this is possible.

My question to you (and others who liked the proposal) is that, what do you expect to do when you open the app and the app loads the position of last read? Do you expect to continue reading **older** toots, or do you expect to read **newer** toots from the remembered position?

**Comment by eamodio** [comment]
For me personally, I always read older to newer, so I would want to continue reading newer posts from that remembered point. Though I would like to see the "remembered" post at the top/near the top and have a few of the older posts visible below it -- since I might not have exactly stopped reading at the top post, but one that was in view when it was remembered.

**Comment by eamodio** [comment]
I would also love it so that I could smoothly scroll up (newer in time) and not have "load more" gap point that happen on Twitter or even other Mastodon clients. Though if "load more" gaps are a must, I would desperately ask that when clicking the "load more" that it would NOT jump to the newest post but instead LEAVE the current scroll position alone.

**Comment by xmflsct** [comment]
> Though if "load more" gaps are a must, I would desperately ask that when clicking the "load more" that it would NOT jump to the newest post but instead LEAVE the current scroll position alone.

Yes I want this too myself. But unfortunately due to limitation of React Native's list component and all other similar libraries, keeping the same position while adding new content **above** is not possible. See this 3 years old issue https://github.com/facebook/react-native/issues/25239. This is the main reason why I did not add in maintain read position feature, because loading newer toot experience is horrible still.

**Comment by eamodio** [comment]
While not ideal, couldn't you save the top post before the load more, and then jump back to that post after? It wouldn't be as exact as the real scroll position but should be a good enough proxy imo.

**Comment by xmflsct** [comment]
Believe me, if you did experience that kind of jumping timeline **every time** you try to load newer toots, you would get mad. So for now, loading newest is the best option that fits most of the user needs. I can keep this issue open though as I do want this feature myself as well.

**Comment by alper** [comment]
I'd also like it to re-open the list I was reading. I don't read my main timeline, so I always have a list selected. Having to select that again on re-opening the app is something of an inconvenience.

**Comment by ushuz** [comment]
> But unfortunately due to limitation of React Native's list component and all other similar libraries, keeping the same position while adding new content **above** is not possible. See this 3 years old issue [facebook/react-native#25239](https://github.com/facebook/react-native/issues/25239).

https://github.com/facebook/react-native/issues/25239#issuecomment-504215686 mentioned a [`maintainVisibleContentPosition`](https://github.com/facebook/react-native/blob/efd39eea6f553638b2430cbf0c3eed519995a940/Libraries/Components/ScrollView/ScrollView.js#L293-L296) on `ScrollView` for iOS, would that help?

---

> My question to you (and others who liked the proposal) is that, what do you expect to do when you open the app and the app loads the position of last read? Do you expect to continue reading **older** toots, or do you expect to read **newer** toots from the remembered position?

I guess it's safe to mirror what mainstream mobile clients like Twitter or Mastodon are doing.

**Comment by xmflsct** [comment]
@ushuz yes `maintainVisibleContentPosition` is already used, however it only works well if the prepended content has low heights. What breaks currently is that if the content height exceeds a certain amount, I don't know how much but roughly more than half of the screen which is quite common for toots. Other tricks have been used such as this suggestion https://github.com/facebook/react-native/issues/25239#issuecomment-504656072, but it still won't guarantee 100% success. I will see if I can come up with some other ideas to work around this.

**Comment by xmflsct** [comment]
Just did a bit more testing - last time I worked on this was probably more than a year ago. It seems like now at least on iOS, maintaining position is more affordable than before. Now at testing, I can safely prepend at least 5 toots without the timeline jumping around. More than that it becomes challenging, I guess because the aggregated height is too much for the calculation.
