### ISSUE TITLE
Server list gets stuck

### ISSUE THREAD

**Issue by goshpolly** [tooot-app/app#494]
I'm not sure where my previous issue has gone, but repeating it. When you add more than about 20 to 25 servers, the list gets stuck in the app and any you add after it disappear. This applies first to servers your browsing and have no login to, and then to servers you actually log into. The only fix is deleting the app and entering all the service again, but then the problem reoccurs.

**Comment by xmflsct** [comment]
hmmm, I think you are posting to the wrong app's repo. tooot does not have feature to add server without logging in.

**Comment by goshpolly** [comment]
Oh! How embarrassing. Feel free to delete this then!

**Comment by xmflsct** [comment]
@goshpolly No worries!
