### ISSUE TITLE
Push notifications 

### ISSUE THREAD

**Issue by kbexit** [tooot-app/app#498]
When I try switching push notifications on, it thinks about it for a second and switches back to off. Can't seem to get it working at all.

Android 13 Pixel 6 Pro.

**Comment by xmflsct** [comment]
Can you use the "contact tooot" option in the app's setting, there includes some debug info so I can look into this further. Thanks.

**Comment by kbexit** [comment]
> Can you use the "contact tooot" option in the app's setting, there includes some debug info so I can look into this further. Thanks.

Sent it!

**Comment by kbexit** [comment]
Did you receive it? 😅

**Comment by xmflsct** [comment]
@kbexit yes, busy on other features first

**Comment by kbexit** [comment]
> @kbexit yes, busy on other features first

Thank you!

**Comment by xmflsct** [comment]
So, looking at the logs, it seems like the instance you are using did not return a piece of data that is required for enabling push notification. As your instance has lots of users, I believe that shall not be a miss configuration of the instance itself. Can you have a try again?

Otherwise, I. have added additional logging for such purpose https://github.com/tooot-app/app/commit/0fd3fcfd3f27fe79ffde4a56f0521ef2b9f34aa1 for any further debugging.

**Comment by kbexit** [comment]
> So, looking at the logs, it seems like the instance you are using did not return a piece of data that is required for enabling push notification. As your instance has lots of users, I believe that shall not be a miss configuration of the instance itself. Can you have a try again?
> 
> Otherwise, I. have added additional logging for such purpose https://github.com/tooot-app/app/commit/0fd3fcfd3f27fe79ffde4a56f0521ef2b9f34aa1 for any further debugging.

I've been trying it over and over again since I posted the bug. Is there anything you want me to try specifically this time?

**Comment by xmflsct** [comment]
Luckily your instance allows registering accounts freely. I have registered an account and found out that, your instance is indeed missing a configuration. I think the best you can do is reaching out to the admin of your instance about missing secrets for push https://docs.joinmastodon.org/admin/config/#secrets.

**Comment by kbexit** [comment]
> Luckily your instance allows registering accounts freely. I have registered an account and found out that, your instance is indeed missing a configuration. I think the best you can do is reaching out to the admin of your instance about missing secrets for push https://docs.joinmastodon.org/admin/config/#secrets.

When you say "instance" are you referring to the server / federation I'm currently on?

**Comment by xmflsct** [comment]
Yes
