### ISSUE TITLE
Bug: Audio of another App stops when I close Tooot

### ISSUE THREAD

**Issue by DerZyklop** [tooot-app/app#499]
Audio stops when I close Tooot. Tested it with these:
**Spotify** music stops when I close tooot. 
**Pocket Casts** podcasts stop when I close tooot.

I think it is related to the fact that I had watched a video inside tooot previously.

After I close the app tooot completely and restart, the issue was gone.

**Comment by DerZyklop** [comment]
It is reproducible on my device. I made a video. If you are interested, tell me. For some reason I cannot post/upload it here.
¯\_(ツ)_/¯

**Comment by xmflsct** [comment]
@de1acr0ix no no, this bug is already there for ages. I actually could not figure out why. Though I did not look into Exponent's source much. If you have any findings in there, please share. Thanks!

**Comment by de1acr0ix** [comment]
@xmflsct Oh okay. I have a feeling that when tooot starts, it is already starting audio session...

**Comment by de1acr0ix** [comment]
@xmflsct Oh okay. I am feeling this is actually an `expo-av` bug. Looking through its source it seems to be setting the audio session mode to `AVAudioSessionCategorySoloAmbient` when app is switched to background. However it does not deactivate the audio session (it never does) and it kinda stops audio playback in other apps. However I still need some more experiments to prove that.

**Comment by de1acr0ix** [comment]
I do see there is a very similar [issue](https://github.com/expo/expo/issues/19042) raised for `expo-av`. It actually mentions the same behavior. I will join the discussion there and see if we can make any progress.

**Comment by de1acr0ix** [comment]
@xmflsct This isn't very new if I am understanding correctly. With https://github.com/expo/expo/pull/16578 `expo-av` stopped deactivating audio session and I believe that is the time when the problem occurs. It happens in March this year.

**Comment by de1acr0ix** [comment]
Well I myself can confirm it is the bug of `expo-av` by debugging tooot on simulator. When it is switched to background its audio session mode is set to `AVAudioSessionCategorySoloAmbient` without deactivating the session.

**Comment by de1acr0ix** [comment]
My comment in `expo-av` issue https://github.com/expo/expo/issues/19042#issuecomment-1336176851. I will try to create a PR there.

**Comment by xmflsct** [comment]
@de1acr0ix Looking forward! Just read through the linked issue in Expo. If it doesn't work out, I can try https://github.com/hirbod/react-native-volume-manager/ as mentioned.

**Comment by xmflsct** [comment]
https://github.com/tooot-app/app/pull/507 fixed the issue, tested through TestFlight. Still yet to try how it works with `DuckOthers`. cc @de1acr0ix

**Comment by xmflsct** [comment]
Confirm fixed in above PR.

**Comment by xmflsct** [comment]
@de1acr0ix that is right. In this case I can change ducking to `DoNotMix`. In this case other audio playback will be stopped whenever a video starts playing in tooot. The other audio playback won't be resumed automatically due to lack of ending audio session in `expo-av`. But at least, closing tooot won't "randomly" stop other audio playback. How does this sound?

**Comment by de1acr0ix** [comment]
@xmflsct Even with `DuckOthers` now closing tooot won’t stop other audio playback as the patch I added should have addressed that issue (which happens regardless the option).

Your proposal does sound better but the behavior needs to be tested. Other audio may still resume after tooot is switched to background.

BTW is there any easier way to test on real iOS device? I have enrolled developer program yesterday but I have to change couple of settings such as bundle id to make it work.

**Comment by xmflsct** [comment]
@de1acr0ix I wish I knew 😂 I still find the whole app signing confusing, so I would not touch it unless it is broken. But if you are aiming for testing locally only, I believe you can change the signing in Xcode to let it manage everything with your account. Currently the signing is managed by fastlane's match so it shows up as incorrect in Xcode.

Unfortunately the simulator does not work like a real device when I tested this issue in particular, FYI.

**Comment by xmflsct** [comment]
@de1acr0ix have you managed to try out the latest build of v4.6.6? How do you think its behaviour now?

**Comment by de1acr0ix** [comment]
> @de1acr0ix have you managed to try out the latest build of v4.6.6? How do you think its behaviour now?

I just tried that. The audio in Spotify stops when starting playing audio/video and won’t resume thereafter, including switching Tooot to background. So far I think this is best we can get without changing `expo-av`.

**Comment by xmflsct** [comment]
@de1acr0ix indeed, until `expo-av` supports resuming (or stopping the session as you found out), it is the best so far. I will close this ticket then. Thanks again for your help!
