### ISSUE TITLE
Poll reply comment not wrapping while typing

### ISSUE THREAD

**Issue by Seanmclem** [tooot-app/app#513]
App v4.6.4
iOS version 

When I see a poll in my feed, I press the comment icon, I am presented with a screen that has; 

the poll title at the top,
The space where I type my reply in the middle,
And a little preview of the poll's post again, near the bottom. 
Keyboard below that. 

So when I type enough in my reply the text box should expand vertically. It doesn't. So as the text wraps to a second or third line, it's still a single line text box and not expanding. _Can only see the first line._ or more accurately, Can see all but the final line

If I add a return character, it suddenly works and shows everything. 

It should already work and show everything as the text wraps to multiple lines. 

Edit. I've encountered more issues there when trying to wrap to a third line, and to select the hidden text. The whole reply area disappeared. 

![image](https://user-images.githubusercontent.com/6831540/205546205-654da694-fe4b-48ec-a544-6173b5c3fda2.jpeg)

**Comment by xmflsct** [comment]
I believe it is a duplicate report as https://github.com/tooot-app/app/issues/513. This is weird, let me look into it further.
