### ISSUE TITLE
Like and boost notification attribution broken

### ISSUE THREAD

**Issue by unixninja92** [tooot-app/app#519]
On Android when I post a toot and then someone likes or boosts it, the notification I get is that `my_username favorited your toot` or `my_username boosted your toot`. This started in the latest version (v4.6.5).

**Comment by jameshart-vistaprint** [comment]
Also seeing this in iOS in v4.6.5.

**Comment by xmflsct** [comment]
Duplicate of https://github.com/tooot-app/app/issues/514, fixed in https://github.com/tooot-app/app/commit/c6e27d6d8845ffd35be26923851d80c04920fccb
