### ISSUE TITLE
4.6.5: Boosted toots are attributed to wrong person

### ISSUE THREAD

**Issue by osmaa** [tooot-app/app#531]
Starting with 4.6.6, boosted toots from someone I don't follow show up on the Following timeline with boost attribution to the original author (at least in most cases), instead of the person I follow whose boost actually caused the toot to appear on my timeline.

**Comment by xmflsct** [comment]
Are you sure you are using 4.6.6? It was a bug in 4.6.5, but fixed since. Otherwise please let me know.

**Comment by osmaa** [comment]
thanks, you're right!
