### ISSUE TITLE
Cannot change language

### ISSUE THREAD

**Issue by Techy-Wu** [tooot-app/app#556]
Cannot change language since the languages list is just a list, whose items cannot be chosen.
不能更改软件语言。在软件设置中的语言列表里，不能选择任何语言，点击待选语言后没有任何反馈。

**Comment by Techy-Wu** [comment]
Things went wrong when it comes to v4.6.4 and later versions.
从4.6.4开始就出现此问题了。

**Comment by xmflsct** [comment]
请升级到到最新版v4.6.6，之前有个bug

**Comment by Techy-Wu** [comment]
这个问题从4.6.4开始就”一直存在“，包括最新的4.6.6版本。

https://user-images.githubusercontent.com/73032687/207757784-12a8cbbc-f463-4857-86ee-020b4bfd9fcc.mp4
