### ISSUE TITLE
Unable to login to a whitelist enabled instance 无法在启用白名单模式的实例中登录

### ISSUE THREAD

**Issue by Techy-Wu** [tooot-app/app#565]
For now I want to use Tooot to get logined to a mastodon instance, yet it seems unable to iditify the instance and make my login.
After I check the logs of the instance it appeares a 401 error while I am going to login with Tooot. The error happened at the path "/api/v1/instance". This error seems, so far, concerning only in Android branch of Tooot. And I also noticed that this problem is not existed in Tusky and latest Mastodon Android. For I haven't received any issues from iOS users using Tooot to browse the website. To another point of view, which means the error is avoidable due to future upgrades of Tooot, I guess? And wishes.
My instance address is s.ourneu.space. Tests token by Tooot team for adaptability is allowed and welcomed.

我尝试使用Tooot登录Mastodon实例时发现似乎Tooot不能正确识别白名单模式下的实例，帮助我成功登录实例更加无从谈起。我检查了实例后台发现在Tooot尝试登录时发生了401错误。具体在访问“/api/v1/instance”时出现了这个错误。目前为止，貌似这个错误只在安卓版本的Tooot中出现，因为使用Tooot访问我的实例的iOS用户们好像并没有向我报告任何使用中的问题。另外，我发现Tusky和最新的Mastodon安卓客户端中都不存在这个问题。换句话说，我觉得这个错误看似是可以通过Tooot软件升级避免的吧？希望能够解决。
我的实例地址是s.ourneu.space。允许且欢迎Tooot团队使用这个实例做适配性测试。

![image](https://user-images.githubusercontent.com/73032687/208230672-30f74b74-8efe-47bb-b9bd-828dd7bea2d2.png)

**Comment by xmflsct** [comment]
Okay so this is not a new issue, https://github.com/tooot-app/app/issues/12. I tested again, seems like logging in does work in whitelist mode. I will see what I can do.
