### ISSUE TITLE
Remove line height

### ISSUE THREAD

**Issue by xmflsct** [tooot-app/app#573]
As suggested https://github.com/tooot-app/app/pull/571#issuecomment-1356772685

It is not needed anymore.

**Comment by xmflsct** [comment]
Experimented a bit, unfortunately it doesn't work well with default line height. With default line height, everything feels too squashed together, making it hard for reading. In this case, line height has to be kept, but need to round it up. Basically making sure all adapative sizes rounded up.

**Comment by de1acr0ix** [comment]
It seems that rounding does not help, while removing line height helps. I am very interested in this behavior and am studying the React Native source.

**Comment by xmflsct** [comment]
@de1acr0ix that is awesome! Looking forward to if you have any findings!
