### ISSUE TITLE
iOS 4.7.0下滑刷新偶發時間軸錯亂

### ISSUE THREAD

**Issue by jimmyorz** [tooot-app/app#574]
![image](https://user-images.githubusercontent.com/66128107/208315817-75438221-0825-4c91-9756-75e30fdc04cf.png)
左圖是正常情況
但下滑刷新後會偶發上半部延遲
然後更新出來的時間軸是錯的
剛剛試了一下大概20-30%機率會發生

![image](https://user-images.githubusercontent.com/66128107/208315822-e6152ae0-cbed-48b0-bc00-1b1691d7ece0.png)
除了首頁跟隨時間軸外，本站和聯邦也有類似情況

https://user-images.githubusercontent.com/66128107/208316102-0c54d039-47d2-4361-82ef-929b4c4678c1.MOV
詳細操作影片

**Comment by xmflsct** [comment]
猜你应该指的是“較新的嘟文”的刷新？
