### ISSUE TITLE
Push notifications settings are frozen [android]

### ISSUE THREAD

**Issue by durka** [tooot-app/app#586]
On the latest version, v4.7.0, none of the notification settings can be changed. All the sliders are grayed out.

![image](https://user-images.githubusercontent.com/47007/208541867-d5bad960-63ca-4aca-a666-cee21c545d1f.png)

**Comment by xmflsct** [comment]
Just released v4.7.1. Can you take a look if it has been fixed?

**Comment by durka** [comment]
It is!
