### ISSUE TITLE
Link with escape codes is broken

### ISSUE THREAD

**Issue by durka** [tooot-app/app#593]
See this toot: https://hachyderm.io/@nova/109547901142966190

Clicking on the link in Tooot goes to https://community.hachyderm.io/blog/2022/12/20/the-queues-%25EF%25B8%258F-down-in-queueville/ which is incorrect (escapes got double-encoded).

The correct link is https://community.hachyderm.io/blog/2022/12/20/the-queues-%EF%B8%8F-down-in-queueville/

**Comment by xmflsct** [comment]
I found this commit https://github.com/tooot-app/app/commit/d2bf27a85acae3aa68f5613cf6f22c27989186b1 😂
