### ISSUE TITLE
Can't follow/unfollow anyone

### ISSUE THREAD

**Issue by durka** [tooot-app/app#597]
Since 4.7.1 getting this error every time. It works in Fedilab so shouldn't be an issue with my instance/account.
![Screenshot_20221221-003151](https://user-images.githubusercontent.com/47007/208829142-48c697b3-d8d9-4b17-aabd-5fb6c0745198.png)
![Screenshot_20221221-003208](https://user-images.githubusercontent.com/47007/208829162-e45f41e0-ac4a-4a4b-b85e-7ed918ea9625.png)

**Comment by xmflsct** [comment]
It is again a platform specific bug...

**Comment by durka** [comment]
@xmflsct I am not quite sure how to build the app from this repo, but if wanted me to try out a pre-release on Android, I'm happy to do that, with build instructions.

**Comment by xmflsct** [comment]
@durka thanks! Just released v4.7.2. I will think about if there is any chance to invite test users next year.
