### ISSUE TITLE
Notification bubbles on iOS do not reset

### ISSUE THREAD

**Issue by jan-vandenberg** [tooot-app/app#598]
The latest Tooot version doesn't seem to reset/clear the iOS notifications?!

![AEB55765-FEA1-4EEB-BBC8-935664964D32 (1)](https://user-images.githubusercontent.com/13764557/208927990-38ef26e6-b21d-4dbe-903d-c316e68dacf9.jpg)

**Comment by xmflsct** [comment]
It should. Though few users are reporting similar issues. Can you tap on the contact tooot within the app so that I get few more info to debug further? Thanks!

**Comment by jan-vandenberg** [comment]
I already did yesterday:
https://mastodon.nl/@jan/109548121912143077

and today (after upgrading, hoping it would fix things):
https://mastodon.nl/@jan/109552189978247128

**Comment by xmflsct** [comment]
Closing as chatted with Jan separately.

**Comment by xmflsct** [comment]
Will properly fix in https://github.com/tooot-app/app/issues/615
