### ISSUE TITLE
Push notification page has no content

### ISSUE THREAD

**Issue by nekokristalo** [tooot-app/app#605]
This issue is still not resolved
![Screenshot_2022-12-22-12-32-08-06_6c6295891ca0cd55c428777b1a9a5436](https://user-images.githubusercontent.com/105288787/209056677-eed7cdc7-b53b-4806-8d9e-d3ce9733adcd.jpg)

**Comment by scottiefalkon** [comment]
Same issue here. Latest Tooot release. Android 13 Dec, Pixel 6 Pro.

**Comment by xmflsct** [comment]
Well I also receive messages from other Android 13 users that, after updating to the latest **v4.7.2**, notification works again. Looking at the code, I don't see how this page can be blank at all, there should at least be some error message..

**Comment by scottiefalkon** [comment]
It's still blank for me too. Pixel 6 Pro on Android 13 latest.

**Comment by ettmetal** [comment]
I am on Android 12, tooot 4.7.2 and this page is blank for me, too. It means I can't enable notifications, or control them in any other way.

**Comment by major** [comment]
I am on tooot 4.7.2 and mastodon 4.0.2 and the push notifications lead to a blank page for me as well. This happens on a Samsung Galaxy phone and tablet with the latest version of Android.

It happens across all of the mastodon servers I've tried, including Fosstodon, ohai.social, mastodon.social, and my own self hosted Mastodon.

I've tried reinstalling the app, clearing all of the storage, and restarting the devices. Push notifications work via other apps (like fedilab) and via the web interface.

I love tooot and would love to help debug this. ❤️

**Comment by olijg** [comment]
I'm on the latest 4.7.2, using android 13 on my Pixel 7 and I'm also seeing this bug

**Comment by fenpaws** [comment]
Same happens to me, I'm on a OnePlus6T with LiniageOS 20 (Android 13). 

tooot version: 4.7.2 
mastodon version: 4.0.2

**Comment by scottiefalkon** [comment]
Update coming soon?

**Comment by xmflsct** [comment]
Yes, this week

**Comment by scottiefalkon** [comment]
Awesome. Thanks.

**Comment by scottiefalkon** [comment]
Did followed hashtags disappear?

**Comment by xmflsct** [comment]
@scottiefalkon you mean in the menu selection? It shouldn't, but I can test more.

Is the push working now? Have you installed from the apk build from GitHub?

**Comment by scottiefalkon** [comment]
Push notification page works fine now. The followed hashtags section is no
longer on the profile page. It is the 4.8 update from the GitHub page.

**Comment by xmflsct** [comment]
@scottiefalkon awesome, thank you! Will take a look.

**Comment by scottiefalkon** [comment]
Thank you.

**Comment by scottiefalkon** [comment]
Ok. The new build fixes the hashtags issue. Thanks for making them
clickable as well. New issue. Banner images show up for no one unless you
tap the blank placeholder. Then they appear. Also. Profile image doesn't
show on bottom profile button. Images attached.

**Comment by scottiefalkon** [comment]
Profile image showed on button after restart. Still no banner images for
any account. Only shows if tapped on.

**Comment by scottiefalkon** [comment]
And now they are all showing. Weird.

**Comment by scottiefalkon** [comment]
Ok. Banner doesn't show on profile edit page. And only shows on any users
page on the second visit. Loading circle shows briefly, then nothing until
second visit. Something is off somewhere. Hate to be a bother. Just trying
to help out. Love the app and improvements.
