### ISSUE TITLE
This is a very cool conversation about pulling in federated content

### ISSUE THREAD

**Issue by xmflsct** [tooot-app/app#638]
### Discussed in https://github.com/tooot-app/app/discussions/637

<div type='discussions-op-text'>

<sup>Originally posted by **michaelperna** December 31, 2022</sup>
https://fedi.simonwillison.net/@simon/109559268498004036

Thoughts on a feature set like this?</div>

**Comment by ushuz** [comment]
I think this feature would be fantastic. It's a real pain point using Mastodon, especially if someone is on a smaller instance or running their own instance. Also, for users that chose to lock their toots, their followers don't have any way to view toots before following.
