### ISSUE TITLE
No settings within the Push Notifications tab

### ISSUE THREAD

**Issue by emilyboda** [tooot-app/app#643]
Using tooot version 4.7.2 and mastodon version 4.0.2. My mastodon server is hachyderm.io. Downloaded from the play store yesterday on my Pixel 7.

The tab looks like this: https://photos.app.goo.gl/fsmV9uhkQj27mcNk7
I clicked here within the main settings page: https://photos.app.goo.gl/fsmV9uhkQj27mcNk7

**Comment by xmflsct** [comment]
Fixed in https://github.com/tooot-app/app/issues/605, release coming.
