### ISSUE TITLE
Links does not work

### ISSUE THREAD

**Issue by yordiak** [tooot-app/app#648]
Redirection of a link posted on a toot does not work. Specifically, when I am clicking on a link that someone mentions on his/her post nothing happens. 

**Update / Workaround**
I managed to 'solve' the problem by doing the followings: 
(a) from the app settings i changed the open link from "inside to app" to "use system browser"
(b) then i reverted to "inside to app"

Info:
Platform: Android 12
Tooot: v 4.8.0
Source: Github

**Comment by xmflsct** [comment]
I guess you are setting your default browser to a none system default, most probably DuckDuckGo?

**Comment by yordiak** [comment]
my default browser is Brave

**Comment by xmflsct** [comment]
Can you try if you can login to a new account? Go into "Switch Account" page, type in any instance, then press "Login". Does it open a browser window? You do no need to actually login to any account, just to verify if the browser can be opened there. Thanks.

**Comment by yordiak** [comment]
I did a clean install and not an update from v 4.7.2 to v 4.8.0, When I launched tooot, then the browser window did open in order to enter my credentials. The problem arose only when I tried to click on a link

**Comment by yordiak** [comment]
This problem is present in the latest build (v 4.8.2). I tried a clean install from playstore. Links does not work, unless I change the option from inside app to system's browser and then, by reverting to the inside app option
