### ISSUE TITLE
No notification on android 12

### ISSUE THREAD

**Issue by yordiak** [tooot-app/app#650]
Here basically I am asking than reporting an issue. Did anyone else faces problems with notifications?

The new version solves the previous bug with the empty notification screen. Now, even though I have enabled notifications I do not receive anything.

**Comment by xmflsct** [comment]
Can you send a support message in the app so I can take a look? The message in the app would include additional troubleshooting data.

**Comment by yordiak** [comment]
how can i do that?

**Comment by xmflsct** [comment]
Go to the Settings in the app, there is a "contact tooot".

**Comment by yordiak** [comment]
ok, i found it. But when I click on the "toot DM" (upper right corner) I get a message "tooting failed"

**Comment by scottiefalkon** [comment]
Same on Android 13. Notification page is functional again, but no notifications come through.

**Comment by xmflsct** [comment]
You can give the latest 4.8.1 a try. You need to disable then enable again within the app.

**Comment by scottiefalkon** [comment]
Working. Banners loading too.
