### ISSUE TITLE
Crash on splash screen

### ISSUE THREAD

**Issue by EdisonJwa** [tooot-app/app#656]
I'm using tooot on iOS and crashed on the splash screen.

Model: `iPhone 13 Pro`
OS: `iOS 16.2(20C65)`
App Version: `4.8.1`

**Comment by xmflsct** [comment]
Yes it is known. A fix has been pushed yesterday and awaiting Apple's review. Mostly the review should be completely in the next few hours.

**Comment by xmflsct** [comment]
4.8.2 is out now, can you have a try and let me know if it is working now? (I hope it does!)
