### ISSUE TITLE
Severe lag in nested threads

### ISSUE THREAD

**Issue by yutotakano** [tooot-app/app#666]
When viewing a post with multiple replies, which are nested and go several levels deep (indicated by the 5 or 6 vertical lines on the left), scroll actions lose framerates and become very laggy. This fixes itself when you scroll to a place where only single or 2nd layer replies are shown on screen.

Presumably it's to do with the number of elements drawn, but it seems like nested post threads increase processing complexity exponentially instead of linearly like with multiple single-deep replies.

Tooot version: v4.8.2

Toot where I experienced this: https://sauropods.win/@futurebird/109698982405188004

**Comment by xmflsct** [comment]
Are you using Android or iOS?

**Comment by yutotakano** [comment]
Ah, Android. I didn't realise tooot was available on iOS, apologies for leaving out that info.

**Comment by xmflsct** [comment]
Just released v4.8.3 on Play Store. Can you give it a try and let me know if it has improved?

**Comment by ottomano** [comment]
Hi all.
I downloaded and tried 4.8.3 but the issue is still present on Android.

I will send you a video via DM on Mastodon.

**Comment by yutotakano** [comment]
Good morning, apologies for the late reply -- I downloaded 4.8.3 too and still face the issue. I've also recorded a screencast ([here](https://gfycat.com/speedysmugblobfish)). You can see how the scroll is smoother at shallower levels, and laggier at deep levels. At first I suspected it was the loading of images and new network content, but I scrolled back and forth around the same place (which should already have downloaded content) it doesn't look like that's the case.

**Comment by xmflsct** [comment]
Problem identified. It relates to the use of `react-native-svg` somehow.
