### ISSUE TITLE
当app设置为软件内打开链接时点击嘟文中的链接没有任何响应

### ISSUE THREAD

**Issue by Odeioikr** [tooot-app/app#669]
经测试在当tooot设置为软件内打开连接时在以下设备上均无法正常打开链接
安卓手机 MIUI Global13.0.5 安卓12
iPad iPadOS 16.2

**Comment by xmflsct** [comment]
多谢反馈！https://github.com/tooot-app/app/commit/613cf1365ce065ed820217bff701bce5ce0aa81f
