### ISSUE TITLE
Empty notification page on Android

### ISSUE THREAD

**Issue by yordiak** [tooot-app/app#679]
This issue seemed to be solved on v4.8.3

Stages to reproduce:
1) Open notification settings,
2) Go back, using the "back" bottom
3) Enter again to notification settings. Now the page is empty

Woraround: Force stop

**Comment by xmflsct** [comment]
Fixed in https://github.com/tooot-app/app/commit/2c96991ca05e6d5bb7d9e4134344e6c4e8a51400
