### ISSUE TITLE
Cannot enable notifications on Android

### ISSUE THREAD

**Issue by yordiak** [tooot-app/app#680]
This issue might be present on v4.8.3 as well

Stage to reproduce:
1) If enabled, disable your notifications
2) Try to enable again Now, the option for enabling notifications is switching off automatically when I try to enable them

**Comment by MarkJR84** [comment]
Same for me in 4.3.4. When I first launch the app and tap on push notifications I'll get a system pop-up message asking if I want to receive notifications from the app. Then inside the push notifications settings when I enable the slider it immediately turns off again.

**Comment by xmflsct** [comment]
Can you try v4.8.5? It should fix a network error in that version. Let me know if it still doesn't work to enable push.

**Comment by MarkJR84** [comment]
Looks like 4.8.5 fixed it, thanks 😊
