### ISSUE TITLE
Empty space instead of custom emojis

### ISSUE THREAD

**Issue by DanielTolentino** [tooot-app/app#691]
There is no display of custom emoji after writing and sending a post. No custom emoji can be seen on the home page, profile, or in opened posts.

**Comment by xmflsct** [comment]
Can you DM a link to your post if it is okay? I cannot reproduce the issue you are describing.

**Comment by DanielTolentino** [comment]
Here's a post https://mastodon.online/@_notDaniel/109779529645247683

Other user that I recommend is facing the same issue
https://bolha.one/@cadusilva/109779420122172573

Link to another post with no custom emoji 
https://bolha.one/@cadusilva/109779416464395883

![Screenshot_20230130-152026.png](https://user-images.githubusercontent.com/5665358/215562356-31c47872-b47e-4e0f-88d3-5a96d0c45947.png)

**Comment by xmflsct** [comment]
hmmm, the emojis are working fine in the emulator, both iOS and Android.

First of all, can you make sure you are on the latest version of the app? If so, what is your Android's version?

**Comment by DanielTolentino** [comment]
![Screenshot_20230131-202013.png](https://user-images.githubusercontent.com/5665358/215906371-2ed4177e-ec83-487f-b25f-1dbb3b75d85f.png)

Stock Android 10 from Motorola. The other user is at Android 12 with a custom ROM.

Already tried do to a clean install of the app, no lucky.
I'll install in other devices and see if works. Strange tho is other people getting same error.  Will investigate further, thanks.

**Comment by DanielTolentino** [comment]
![IMG-20230131-WA0004.jpg](https://user-images.githubusercontent.com/5665358/215908128-934fb5cc-cb1e-462e-8568-e0551ac4e793.jpg)

Installed from GitHub, Samsung with android 13
Same problem.
Different network.

Installed again from Google Play too, same problem.

This doesn't make sense, if anything changes I'll update this issue or close it.

**Comment by xmflsct** [comment]
Keep it open, but do let me know if you find out something more, like different server, etc.

**Comment by cadusilva** [comment]
Hello, I'm the author of some of the links and I'm experience the same issue as @DanielTolentino. Below is a video showing me typing a toot with a custom and animated emoji and then it ends up "missing" from the post after publishing. Actually it isn't really missing, it's there, just invisible. Other apps and the web interface shows it just fine:

![image](https://user-images.githubusercontent.com/8684263/215911675-c563af19-305d-431c-aac0-5ab9dab37494.png)

[video](https://user-images.githubusercontent.com/8684263/215911837-b3c79d18-0709-4e5f-b8b8-d149d0ca10a2.mp4)

**Comment by xmflsct** [comment]
Confirm I can reproduce the issue with the "real devices" provided by BrowserStack. Will look into why.
