### ISSUE TITLE
No notifications on android 

### ISSUE THREAD

**Issue by MarkJR84** [tooot-app/app#692]
I reinstalled the app yesterday but I'm not getting notifications.
I have made sure notifications are turned on in tooot settings and they are enabled in android system settings.
I'm on a pixel 6 pro on android 13 fully up to date. Current app version is 4.8.6

**Comment by MarkJR84** [comment]
I tried that earlier this morning. I had a number of notifications through on the mastodon app, but nothing from tooot I'm afraid.

However, I have disabled it and re-enabled notifications within tooot again and I'll update this thread later today.

**Comment by xmflsct** [comment]
Alternatively, log out of the account you are not receiving push, then log in and enable. That should fix any potential issue between your instance and tooot's server.

**Comment by yordiak** [comment]
> Alternatively, log out of the account you are not receiving push, then log in and enable. That should fix any potential issue between your instance and tooot's server.

I tried both to disable-re-enable notifications and logout-login to by instance. The problem persists. I am on android 12 (realme 8i), instance: kafeneio.social.

I have not tried it with other instance, though

**Comment by MarkJR84** [comment]
Yeah I tried log out and logging in again a number of times, along with clearing cache and data, uninstalling-reinstalling etc but no luck I'm afraid.
Instance: mastodon.lol

**Comment by xmflsct** [comment]
Can you tap on the "Contact tooot" in the app's setting page? There includes few more troubleshooting details. Thanks.

**Comment by MarkJR84** [comment]
I have sent the DM to you. Thanks
