### ISSUE TITLE
No notification on iOS 16.3

### ISSUE THREAD

**Issue by yordiak** [tooot-app/app#701]
I am running the latest version of tooot on an iphone 11 (iOS 16.3). The problem is that I do not receive any notification. I tried to disable and re-enable notifications but the problem persists.

Is it possible for the problem to be on the instance side? (kafeneio.social)

**Comment by xmflsct** [comment]
Likely yes on the instance side somehow stopped sending messages to tooot's server.

What you could try is, logging out of the account and re-login, then enable push for this account. Let me know if this works.

**Comment by yordiak** [comment]
I tried it but without success. I send you a DM through the app
