### ISSUE TITLE
[Android] only buttons of first sub-toots work

### ISSUE THREAD

**Issue by hadilq** [tooot-app/app#706]
After clicking on a toot, on the "Discussions" page, only buttons of sub-toots, that were visible at the start of the page, work. After scrolling to sub-toots that were not visible in the start, no button works, including "like", "share", "reply", or even clicking on the toot itself. By sub-toots I mean reply of replies, and their replies.

I'm not sure, but it looks like the listener callbacks are not set while scrolling.

**Comment by xmflsct** [comment]
Which version are you on?

**Comment by ottomano** [comment]
> Which version are you on?

Hi, I have the same issue.
I'm the one who has sent you a video via DM on Mastodon.

I'm on 4.8.8 but the issue started when you added the new "threads" view.

Best regards

N.

**Comment by hadilq** [comment]
Yep! v4.8.8 has this problem. Also I forgot to mention that I'm thankful. You did great.
