### ISSUE TITLE
Fetch toot preview from link in toot

### ISSUE THREAD

**Issue by joch** [tooot-app/app#707]
Hi!

if someone posts a toot with a link to another toot, it would be awesome if that could be fetched inline. Example from ice cubes:

![C5A9E2C8-2123-4318-AE7B-7C0ACAF95C60](https://user-images.githubusercontent.com/1849369/219947291-b6d08477-5489-4bc7-92de-682e27bd7d1e.png)

Edit: Looks like it does fetch toot link content, maybe it’s just a bit flakey.

**Comment by xmflsct** [comment]
Yes indeed, it is already a feature for quite some time. Most of the time the fetch could be successful, but in some cases the fetch might fail, depending on the network condition.
