### ISSUE TITLE
[Feature Request] Latest tweet when fetching the home button

### ISSUE THREAD

**Issue by yordiak** [tooot-app/app#708]
Updating my timeline loads only the 40 tweets earlier than my last visited one. That means that if I want to go to the most recent tweet I need to click on the home button several times.

It would bre really helpful if: 
1. The first tweet from opening the app is the last one you saw before closing the app (current behavior)
2. By clicking the home button, then most recent tweet appears

**Comment by xmflsct** [comment]
Added a change that by clicking the bottom nav button as you mentioned, the auto refetch would stop. Then you can choose to refresh to the latest, or continue loading newer toots only.
