### ISSUE TITLE
Your phone does not support tooot's push notification

### ISSUE THREAD

**Issue by yordiak** [tooot-app/app#711]
This is quite strange. 

On the previous version (4.8.8) I could receive push notifications. After a clean install (v4.9.0) I receive the following error when I try to enable push notifications:

> Your phone does not support tooot's push notification

device: iphone 11
os: ios 16.3.1

**Comment by tavi-vi** [comment]
same thing here, but with an iphone 8 on ios 16.2

**Comment by nuclearfall** [comment]
Same here on iPhone 13. 16.2 and 16.3. It's a shame because notifications have previously been available. I have an Apple Watch and they appeared on it, which was lovely.

**Comment by xmflsct** [comment]
https://github.com/tooot-app/app/commit/0db7f0c40ab1c3a90c860588a5a92e6e26e7bc50 should finally fixed the issue. Awaiting for the approval of v4.9.1 from App Store then you can give it a go.

**Comment by xmflsct** [comment]
It is released. Let me know if it is working now.

**Comment by chenew** [comment]
Just updated to v4.9.1 and push notification options are back.
