### ISSUE TITLE
Some toots on Notifications screen are greyed out (iPhone/dark mode)

### ISSUE THREAD

**Issue by earlruby** [tooot-app/app#736]
On an iPhone in dark mode some toots on the notifications screen are greyed out, and others are not. 

Here are three notifications that a post of mine was favorited, all grey:

![2023-04-28 17 05 57](https://user-images.githubusercontent.com/1270169/235272038-6c8b4e38-8caf-427b-b633-ba2c73fb77f9.jpg)

Here's a poll I responded to (greyed) and a response (full brightness):

![2023-04-28 17 10 39](https://user-images.githubusercontent.com/1270169/235272116-728b8f18-046e-40fe-964e-81b69c3076a9.png)

Seems like an odd design choice. Is this a bug or intentional?

**Comment by xmflsct** [comment]
Yes this was intended, greying out **your own** toots, helping focus on whether your toot was reposted, etc. But from your screenshot, a poll you participated in also got greyed out which is not intended.
