### ISSUE TITLE
Feature request: set focus point for shared images 

### ISSUE THREAD

**Issue by satmandu** [tooot-app/app#738]
Tusky has a feature where you can select a focus point for shared images.

It would be nice for Tooot to be able to do that as well.

![Screenshot_20230514-114917.png](https://github.com/tooot-app/app/assets/1096701/110ec8be-2596-4ca3-8f41-111c7cffea51)

**Comment by satmandu** [comment]
![Screenshot_20230514-115023.png](https://github.com/tooot-app/app/assets/1096701/7cfea08d-4f7c-4ab6-a3de-d4ca65136494)

**Comment by xmflsct** [comment]
This feature was available from the beginning, but remove a while ago. The reason being that, many third party apps do not respect set focus point, and each app has its own way of cropping images. Hence it was decided to remove this feature.
