### ISSUE TITLE
neodb api change

### ISSUE THREAD

**Issue by alphatownsman** [tooot-app/app#741]
hey, neodb are adding/changing some api endpoints, more on that https://neodb.social/developer/

the change should be rather straight forward, let me know if anything I can clarify or help you migrate. 

the deprecated APIs will be kept until Aug 1st.

**Comment by xmflsct** [comment]
Upgrading the API calls now, and adding the new `performance` type. I notice that the UI will include a list of "productions" while the API does not include. Is there a plan to expose such information when querying `performance`? It can be similar to the `seacon_count` in the `tv` entity, exposing a `production_count` in `performance`.
