### ISSUE TITLE
功能请求：是否考虑增加支持 Proxy

### ISSUE THREAD

**Issue by v03413** [tooot-app/app#747]
由于众所周知的原因，在某些网络环境下下难免会遇到各种形式的干扰，虽然我相信大部分使用`Mastodon`的玩家都具备基本的科学素养，但相比依赖系统或者其它第三方软件实现网络的二次代理，如果软件自身原生支持，那自然是更好的，例如 Telegram WeChat 都支持 Socks5 代理。

❤️ 再次感谢作者，App 非常不错  🙏

**Comment by xmflsct** [comment]
tooot自带🆓🪜

在不挂🪜的时候可以在应用里的设置菜单里启用。如果看不到这个选项的话可以发邮件至support@tooot.app

**Comment by v03413** [comment]
> tooot自带🆓🪜
> 
> 在不挂🪜的时候可以在应用里的设置菜单里启用。如果看不到这个选项的话可以发邮件至[support@tooot.app](mailto:support@tooot.app)

好的，非常感谢，已经注意到了这个功能；虽然但是，除了大内网，有时候还有小内网，比如某些企业白名单局域网内，如果可以支持自定义，可以非常方便我们摸🐟的，哈哈～

**Comment by xmflsct** [comment]
白名单制度简直太恶劣了…我看看，可能不一定好实现
