### ISSUE TITLE
App force closing 4.10.2

### ISSUE THREAD

**Issue by Shadowvaporwarez** [tooot-app/app#761]
On the latest app version, the app is force closing as soon as I log in, so I've had to downgrade back to 4.10.2

I'm on Android 13, Oxygen OS 13.1

**Comment by uroybd** [comment]
Having the same issue.

Android 13. MIUI 14.0.3

**Comment by xmflsct** [comment]
Should be fixed in https://github.com/tooot-app/app/commit/9f8064ded4a26a2c0cb42f3e1d8cbebef67c1787.
